[package]
name = "traq-markdown-processor"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "Parse once, render notification text and extract references in Rust."

[features]
contracts = ["dep:ts-rs", "dep:schemars", "traq-markdown-processing/contracts"]

[dependencies]
traq-markdown-grammar = { path = "../grammar" }
traq-markdown-processing = { path = "../processing" }
markdown-renderer = { git = "https://github.com/traq-markdown-parser/core.git", rev = "1ccba0a7a63f7128873b4490e8f0b1c5b8714099", version = "0.1.0" }
markdown-extractor = { git = "https://github.com/traq-markdown-parser/core.git", rev = "1ccba0a7a63f7128873b4490e8f0b1c5b8714099", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
ts-rs = { version = "12", optional = true, features = ["serde-json-impl"] }
schemars = { version = "1.2.2", optional = true }

[dev-dependencies]
serde_json = "1"
