[package]
name = "traq-markdown-processing"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
contracts = ["markdown-trap-extraction/contracts", "dep:ts-rs", "dep:schemars"]


[dependencies]
serde = { version = "1", features = ["derive"] }
ts-rs = { version = "12", optional = true, features = ["serde-json-impl"] }
schemars = { version = "1.2.2", optional = true }
markdown-trap-contracts = { git = "https://github.com/traq-markdown-parser/trap-extension.git", rev = "c7ed47d4739765e6bd9e25468d4c9dfa4f271d61", version = "0.1.0" }
markdown-ast = { git = "https://github.com/traq-markdown-parser/core.git", rev = "1ccba0a7a63f7128873b4490e8f0b1c5b8714099", version = "0.1.0" }
markdown-commonmark-text = { git = "https://github.com/traq-markdown-parser/commonmark.git", rev = "00fdb814d980ee4e326eb6a05d8ff4bba289d291", version = "0.1.0" }
markdown-commonmark-contracts = { git = "https://github.com/traq-markdown-parser/commonmark.git", rev = "00fdb814d980ee4e326eb6a05d8ff4bba289d291", version = "0.1.0" }
markdown-generic-text = { git = "https://github.com/traq-markdown-parser/commonmark.git", rev = "00fdb814d980ee4e326eb6a05d8ff4bba289d291", version = "0.1.0" }
markdown-trap-text = { git = "https://github.com/traq-markdown-parser/trap-extension.git", rev = "c7ed47d4739765e6bd9e25468d4c9dfa4f271d61", version = "0.1.0" }
markdown-trap-extraction = { git = "https://github.com/traq-markdown-parser/trap-extension.git", rev = "c7ed47d4739765e6bd9e25468d4c9dfa4f271d61", version = "0.1.0" }
markdown-renderer = { git = "https://github.com/traq-markdown-parser/core.git", rev = "1ccba0a7a63f7128873b4490e8f0b1c5b8714099", version = "0.1.0" }
markdown-extractor = { git = "https://github.com/traq-markdown-parser/core.git", rev = "1ccba0a7a63f7128873b4490e8f0b1c5b8714099", version = "0.1.0" }

[dev-dependencies]
traq-markdown-grammar = { path = "../grammar" }
serde_json = "1"
