// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkForm } from "./LinkForm.js";

export type Link = { destination: string, title: string | null, form: LinkForm, };
