// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParseError = { "code": "invalid_utf8" } | { "code": "resource_limit", resource: string, } | { "code": "internal_error" };
